#!/bin/bash

curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/AdditionalProductInformation.xsd --output AdditionalProductInformation.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Amazon.xsd --output Amazon.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-base.xsd --output base.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-envelope.xsd --output envelope.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-header.xsd --output header.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Arts.xsd --output Arts.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/AttributeGroups.xsd --output AttributeGroups.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/AutoAccessory.xsd --output AutoAccessory.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Baby.xsd --output Baby.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Beauty.xsd --output Beauty.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Books.xsd --output Books.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CameraPhoto.xsd --output CameraPhoto.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CatPIL.xsd --output CatPIL.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CE.xsd --output CE.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ClothingAccessories.xsd --output ClothingAccessories.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Coins.xsd --output Coins.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Collectibles.xsd --output Collectibles.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Computers.xsd --output Computers.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Customer.xsd --output Customer.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CustomerAddress.xsd --output CustomerAddress.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/EducationSupplies.xsd --output EducationSupplies.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/EntertainmentCollectibles.xsd --output EntertainmentCollectibles.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/EUCompliance.xsd --output EUCompliance.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/FBA.xsd --output FBA.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FoodAndBeverages.xsd --output FoodAndBeverages.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/FoodServiceAndJanSan.xsd --output FoodServiceAndJanSan.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FulfillmentCenter.xsd --output FulfillmentCenter.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FulfillmentOrderCancellationRequest.xsd --output FulfillmentOrderCancellationRequest.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FulfillmentOrderRequest.xsd --output FulfillmentOrderRequest.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Furniture.xsd --output Furniture.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/GiftCards.xsd --output GiftCards.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Gourmet.xsd --output Gourmet.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Health.xsd --output Health.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Home.xsd --output Home.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/HomeImprovement.xsd --output HomeImprovement.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Image.xsd --output Image.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Industrial.xsd --output Industrial.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Inventory.xsd --output Inventory.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Item.xsd --output Item.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Jewelry.xsd --output Jewelry.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/LabSupplies.xsd --output LabSupplies.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/LargeAppliances.xsd --output LargeAppliances.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Lighting.xsd --output Lighting.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/LightMotor.xsd --output LightMotor.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Listings.xsd --output Listings.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ListingSummary.xsd --output ListingSummary.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Loyalty.xsd --output Loyalty.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Luggage.xsd --output Luggage.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/LuxuryBeauty.xsd --output LuxuryBeauty.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/MaterialHandling.xsd --output MaterialHandling.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/MechanicalFasteners.xsd --output MechanicalFasteners.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Miscellaneous.xsd --output Miscellaneous.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Motorcycles.xsd --output Motorcycles.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/MultiChannelOrderReport.xsd --output MultiChannelOrderReport.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Music.xsd --output Music.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/MusicalInstruments.xsd --output MusicalInstruments.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/NavigationReport.xsd --output NavigationReport.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Offer.xsd --output Offer.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Office.xsd --output Office.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderAcknowledgement.xsd --output OrderAcknowledgement.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderAdjustment.xsd --output OrderAdjustment.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderFulfillment.xsd --output OrderFulfillment.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderNotificationReport.xsd --output OrderNotificationReport.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderReport.xsd --output OrderReport.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Outdoors.xsd --output Outdoors.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Override.xsd --output Override.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/PaymentMethod.xsd --output PaymentMethod.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/PetSupplies.xsd --output PetSupplies.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/PowerTransmission.xsd --output PowerTransmission.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Price.xsd --output Price.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProcessingReport.xsd --output ProcessingReport.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Product.xsd --output Product.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProductAttributes.xsd --output ProductAttributes.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProductClothing.xsd --output ProductClothing.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProductImage.xsd --output ProductImage.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/ProfessionalHealthCare.xsd --output ProfessionalHealthCare.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/RawMaterials.xsd --output RawMaterials.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Relationship.xsd --output Relationship.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ReverseFeed.xsd --output ReverseFeed.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/SettlementReport.xsd --output SettlementReport.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Shoes.xsd --output Shoes.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Sports.xsd --output Sports.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/SportsMemorabilia.xsd --output SportsMemorabilia.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Store.xsd --output Store.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/SWVG.xsd --output SWVG.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_7/TestOrderRequest.xsd --output TestOrderRequest.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ThreeDPrinting.xsd --output ThreeDPrinting.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/TiresAndWheels.xsd --output TiresAndWheels.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Tools.xsd --output Tools.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Toys.xsd --output Toys.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ToysBaby.xsd --output ToysBaby.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/TypeDefinitions.xsd --output TypeDefinitions.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Video.xsd --output Video.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/WebstoreItem.xsd --output WebstoreItem.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/WineAndAlcohol.xsd --output WineAndAlcohol.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Wireless.xsd --output Wireless.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/AdditionalProductInformation.xsd --output AdditionalProductInformation.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Arts.xsd --output Arts.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Baby.xsd --output Baby.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Books.xsd --output Books.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Coins.xsd --output Coins.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/EUCompliance.xsd --output EUCompliance.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/EducationSupplies.xsd --output EducationSupplies.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FBA.xsd --output FBA.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FoodServiceAndJanSan.xsd --output FoodServiceAndJanSan.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/GiftCards.xsd --output GiftCards.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Luggage.xsd --output Luggage.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Motorcycles.xsd --output Motorcycles.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Outdoors.xsd --output Outdoors.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/PowerTransmission.xsd --output PowerTransmission.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProfessionalHealthCare.xsd --output ProfessionalHealthCare.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/RawMaterials.xsd --output RawMaterials.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/SportsMemorabilia.xsd --output SportsMemorabilia.xsd
curl https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/TestOrderRequest.xsd --output TestOrderRequest.xsd
curl https://www.w3.org/TR/xmlenc-core/xenc-schema.xsd --output xenc-schema.xsd
curl https://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd --output xmldsig-core-schema.xsd