#!/bin/bash

http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/AdditionalProductInformation.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Amazon.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-base.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-envelope.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-header.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Arts.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/AttributeGroups.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/AutoAccessory.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Baby.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Beauty.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Books.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CameraPhoto.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CatPIL.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CE.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ClothingAccessories.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Coins.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Collectibles.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Computers.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Customer.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CustomerAddress.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/EducationSupplies.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/EntertainmentCollectibles.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/EUCompliance.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/FBA.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FoodAndBeverages.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/FoodServiceAndJanSan.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FulfillmentCenter.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FulfillmentOrderCancellationRequest.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FulfillmentOrderRequest.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Furniture.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/GiftCards.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Gourmet.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Health.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Home.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/HomeImprovement.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Image.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Industrial.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Inventory.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Item.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Jewelry.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/LabSupplies.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/LargeAppliances.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Lighting.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/LightMotor.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Listings.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ListingSummary.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Loyalty.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Luggage.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/LuxuryBeauty.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/MaterialHandling.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/MechanicalFasteners.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Miscellaneous.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Motorcycles.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/MultiChannelOrderReport.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Music.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/MusicalInstruments.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/NavigationReport.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Offer.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Office.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderAcknowledgement.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderAdjustment.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderFulfillment.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderNotificationReport.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderReport.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Outdoors.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Override.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/PaymentMethod.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/PetSupplies.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/PowerTransmission.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Price.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProcessingReport.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Product.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProductAttributes.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProductClothing.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProductImage.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/ProfessionalHealthCare.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/RawMaterials.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Relationship.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ReverseFeed.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/SettlementReport.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Shoes.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Sports.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/SportsMemorabilia.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Store.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/SWVG.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_7/TestOrderRequest.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ThreeDPrinting.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/TiresAndWheels.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Tools.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Toys.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ToysBaby.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/TypeDefinitions.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Video.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/WebstoreItem.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/WineAndAlcohol.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Wireless.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/AdditionalProductInformation.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Arts.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Baby.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Books.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Coins.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/EUCompliance.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/EducationSupplies.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FBA.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FoodServiceAndJanSan.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/GiftCards.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Luggage.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Motorcycles.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Outdoors.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/PowerTransmission.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProfessionalHealthCare.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/RawMaterials.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/SportsMemorabilia.xsd
http --download https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/TestOrderRequest.xsd
http --download https://www.w3.org/TR/xmlenc-core/xenc-schema.xsd
http --download https://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd